export const sideArray = [
  {
    id: 1,
    language: "html",
    introduction: [
      "HTML Introduction",
      "HTML Working",
      "HTML Prerequisite",
      "HTML Document Structure",
      "HTML Page Structure",
      "HTML Editors",
      "HTML View Source",
      "HTML Tags",
      "HTML Elements",
      "VS Code Installation",
    ],
    basic_tag: [
      "Skeletal Tags",
      "Heading Tags",
      "Paragraph Tag",
      "Horizontal Line Tag",
      "Line Break Tag",
      "Center Tag",
      "Preserve Formatting Tag",
    ],
    formatingTags: [
      "Monospaced Font",
      "Text Abbreviation Tag",
      "Acronym Tag",
      "Text tags",
    ],
    quotations: [
      "Blockquote Tag",
      "Quote Tag",
      "Text Citation Tag",
      "Text Direction Tag",
      "Address Text Tag",
      "Code Tag",
    ],
    attributies: [
      "HTML Attributes",
      "HTML Core Attributes",
      "HTML Internationalization Attributes",
      "HTML Generic Attributes",
    ],
    links: ["HTML Links"],
    comments: ["HTML Comments"],
    images: ["HTML Images"],
    lists: [
      "HTML Lists",
      "HTML Unordered List",
      "HTML Ordered List",
      "HTML Definition List",
    ],
    tables: ["HTML Tables"],
    blockelement: ["HTML Block Elements"],
    inlineelement: ["HTML Inline Elements"],
    form: ["Introduction", "More on forms"],
  },
  {
    id: 2,
    language: "css",
    introduction: [
      "Information & History",
      "Your first CSS website",
      "How CSS works?",
      "Ways to add CSS",
      "CSS Selectors",
      "CSS Comments",
    ],
    properties: [
      "CSS Colors",
      "CSS Backgrounds",
      "CSS Borders",
      "CSS Images",
      "CSS Video Embedding",
      "CSS Fonts",
      "CSS Text Styling",
      "CSS Padding",
      "CSS Margin",
      "CSS Hover",
      "CSS Cursors",
      "CSS Links",
      "CSS Combinators",
      "CSS Pseudo-classes",
      "CSS Buttons",
      "CSS Overflow",
      "CSS Float",
      "CSS !important",
      "CSS Maths Functions",
      "CSS Size",
      "CSS Positioning",
      "CSS Z-index",
      "CSS Forms",
      "CSS Navigation Bar",
    ],
    desigining: ["CSS Display", "CSS FlexBox", "CSS Grid", "CSS Media Queries"],
    advance_topic: [
      "CSS 2D Transform",
      "CSS Transitions",
      "CSS Border Images",
      "CSS Gradients",
      "CSS Inherit",
      "CSS Shadows",
      "CSS ToolTip Text",
      "CSS Masking",
      "CSS Pagination",
      "CSS Media Queries Advanced",
      "CSS Animations",
    ],
    faqs: ["Questions"],
  },
];
