export const sideArray = [
  {
    id: 1,
    language: "html",
    introduction: [

      "HTML Introduction",
      "HTML Working",
      "HTML Prerequisite",
      "HTML Document Structure",
      "HTML Page Structure",
      "HTML Editors",
      "HTML View Source",
      "HTML Tags",
      "HTML Elements",
      "VS Code Installation",
    ],
    'HTML BASIC TAGS': [
      "Skeletal Tags",
      "Heading Tags",
      "Paragraph Tag",
      "Horizontal Line Tag",
      "Line Break Tag",
      "Center Tag",
      "Preserve Formatting Tag",
    ],
    "HTML FORMATTING TAGS": [
      "Monospaced Font",
      "Text Abbreviation Tag",
      "Acronym Tag",
      "Text tags",
    ],
    '"HTML QUOTATIONS"': [
      "Blockquote Tag",
      "Quote Tag",
      "Text Citation Tag",
      "Text Direction Tag",
      "Address Text Tag",
      "Code Tag",
    ],
    "HTML ATTRIBUTES": [
      "HTML Attributes",
      "HTML Core Attributes",
      "HTML Internationalization Attributes",
      "HTML Generic Attributes",
    ],
    "HTML Links": ["HTML Links"],
    "HTML Comments": ["HTML Comments"],
    "HTML Images": ["HTML Images"],
    "HTML LISTS": [
      "HTML Lists",
      "HTML Unordered List",
      "HTML Ordered List",
      "HTML Definition List",
    ],
    "HTML Tables": ["HTML Tables"],
    "HTML Block Elements": ["HTML Block Elements"],
    "HTML Inline Elements": ["HTML Inline Elements"],
    "HTML FORMS": ["Introduction", "More on forms"],
  },
  {
    id: 2,
    language: "css",
    introduction: [
      "Information & History",
      "Your first CSS website",
      "How CSS works?",
      "Ways to add CSS",
      "CSS Selectors",
      "CSS Comments",
    ],
    "CSS Properties": [
      "CSS Colors",
      "CSS Backgrounds",
      "CSS Borders",
      "CSS Images",
      "CSS Video Embedding",
      "CSS Fonts",
      "CSS Text Styling",
      "CSS Padding",
      "CSS Margin",
      "CSS Hover",
      "CSS Cursors",
      "CSS Links",
      "CSS Combinators",
      "CSS Pseudo-classes",
      "CSS Buttons",
      "CSS Overflow",
      "CSS Float",
      "CSS !important",
      "CSS Maths Functions",
      "CSS Size",
      "CSS Positioning",
      "CSS Z-index",
      "CSS Forms",
      "CSS Navigation Bar",
    ],
    "CSS Designing": ["CSS Display", "CSS FlexBox", "CSS Grid", "CSS Media Queries"],
    "CSS Advance Topics": [
      "CSS 2D Transform",
      "CSS Transitions",
      "CSS Border Images",
      "CSS Gradients",
      "CSS Inherit",
      "CSS Shadows",
      "CSS ToolTip Text",
      "CSS Masking",
      "CSS Pagination",
      "CSS Media Queries Advanced",
      "CSS Animations",
    ],
    "CSS FAQs": ["Questions"],
  },
  {
    id: 3,
    language: "jsvascript",
    INTRODUCTION: [
      "JS Introduction",
      "JS Execution",
      "Node.js Installation",
    ],
    "JAVASCRIPT VARIABLES": [
      "What are Variables?",
      "Variable Naming Rules",
      "var vs let vs const",
      "Primitives and Objects",
      "Operators and Expressions"
    ],
    "JAVASCRIPT BASICS": [
      "If else conditionals",
      "If else ladder",
      "Switch case",
      "Ternary Operator",
      "For Loops",
      "While Loop",
      "Functions"
    ],
    "JAVASCRIPT OBJECTS": [
      "Strings",
      "Arrays and Array Methods",
      "Loops with Arrays",
      "Map, Filter and Reduce",
      "Date",
      "Math",
      "Number",
      "Boolean"
    ],
    "DOM & BOM": [
      "Window Object",
      "History Object",
      "Navigator Object",
      "Screen Object",
      "Document Object",
      "getElementbyId",
      "getElementsByClassName",
      "getElementsByName",
      "getElementsByTagName",
      "innerHTML",
      "outerHTML",
    ],
    OOPs: [
      "Class",
      "Objects",
      "Constructor",
      "Static Method",
      "Encapsulation",
      "Inheritance",
      "Polymorphism",
      "Abstraction"
    ]

  },
  {
    id: 4,
    language: "react",
    " React Tutorial": [
      "React Home",
      "React Setup",
      "React Getting Started",
      "React ES6",
      "React Render HTML",
      "React JSX",
      "React Components",
      "React Class",
      "React Props",
      "React Events",
      "React Conditional",
      "React Lists",
      "React Forms",
      "React Router",
      "React Memo",
      "React CSS Styling",
    ],
    " React Hooks": [
      "What is a Hook?",
      "React useState Hook",
      "React useEffect Hook",
      "React useContext",
      "React useRef",
      "React useReducer",
      "React useCallback",
      "React useMemo",
    ]
  }
];
